### PR TITLE
link updates

### PR DESCRIPTION
**Pull request by isunaslabs**
-made some URL updates

### CODE REVIEW

**Comment by isunaslabs** [comment]
@1022ranji  and @wuminzhe  please help me reviewing this PR

**Comment by 1022ranji** [comment]
image
image

1. Guide 和 API 前面加一下 “01” 和 “02”
2. 少了 “>”

**Comment by isunaslabs** [comment]
Oh! I didn't notice those changes. I'll update them now

**Comment by isunaslabs** [comment]
@1022ranji  please help me reviewing this

**Review by 1022ranji — APPROVED** [review]

**Comment by isunaslabs** [comment]
@wuminzhe  please help me reviwing this code/

**Pull request merged**
