### PR TITLE
Plo nft rewards claim

### PR DESCRIPTION
**Pull request by JayJay1024**

### CODE REVIEW

**Review by xiaoch05 — APPROVED** [review]

**Comment by xiaoch05** [comment]
Only one question, if someone didnot contribute, but send a remark tx "NFT amount: 1; Rewards receiving address: 0x". Whether will it be filtered.

**Comment by 1022ranji** [comment]
image
这两个面板的RING/KTON 的奖励最好也变成是0，我们将不会发放这部分奖励

**Comment by 1022ranji** [comment]
image
领取完成后，上图中的提示文字需要改动下，如下图所示：
image

**Comment by JayJay1024** [comment]
> Only one question, if someone didnot contribute, but send a remark tx "NFT amount: 1; Rewards receiving address: 0x". Whether will it be filtered.

it will be filtered out when export into csv file

**Review by 1022ranji — APPROVED** [review]

**Pull request merged**
